profile: coverage.out

threshold:
  total: 70

exclude:
  paths:
    - ^cmd
    - ^configs
    - ^docs
    - ^internal/app
    - ^internal/config
    - ^internal/domain
    - ^internal/server
    - ^migrations
    - ^pkg
    - ^tests
