// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/shortener_mocks.go -package=mock_shortener_service
//

// Package mock_shortener_service is a generated GoMock package.
package mock_shortener_service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUrlShortener is a mock of UrlShortener interface.
type MockUrlShortener struct {
	ctrl     *gomock.Controller
	recorder *MockUrlShortenerMockRecorder
	isgomock struct{}
}

// MockUrlShortenerMockRecorder is the mock recorder for MockUrlShortener.
type MockUrlShortenerMockRecorder struct {
	mock *MockUrlShortener
}

// NewMockUrlShortener creates a new mock instance.
func NewMockUrlShortener(ctrl *gomock.Controller) *MockUrlShortener {
	mock := &MockUrlShortener{ctrl: ctrl}
	mock.recorder = &MockUrlShortenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlShortener) EXPECT() *MockUrlShortenerMockRecorder {
	return m.recorder
}

// CreateShortURL mocks base method.
func (m *MockUrlShortener) CreateShortURL(ctx context.Context, full string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortURL", ctx, full)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShortURL indicates an expected call of CreateShortURL.
func (mr *MockUrlShortenerMockRecorder) CreateShortURL(ctx, full any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortURL", reflect.TypeOf((*MockUrlShortener)(nil).CreateShortURL), ctx, full)
}

// GetFullURL mocks base method.
func (m *MockUrlShortener) GetFullURL(ctx context.Context, short string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullURL", ctx, short)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullURL indicates an expected call of GetFullURL.
func (mr *MockUrlShortenerMockRecorder) GetFullURL(ctx, short any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullURL", reflect.TypeOf((*MockUrlShortener)(nil).GetFullURL), ctx, short)
}
