# Server config
server:
  read_timeout: 4s
  write_timeout: 10s
  max_header_bytes: 1048576 # 1 MB
  time_for_graceful_shutdown: 10s # seconds
  read_header_timeout: 2s # seconds
  idle_timeout: 60s # seconds

# Logger config
logger:
  level: info
  format: text

# CORS policy
cors:
  allowed_origin: http://localhost:8080
  allow_credentials: true
  allowed_headers:
    - Content-Type
    - Content-Length
    - Authorization
    - X-API-Key
    - Accept
    - Origin
    - User-Agent
  allowed_methods:
    - GET
    - POST
  max_age: 24h

# Postgres config
postgres:
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5m # seconds, minutes
  conn_max_idle_lifetime: 2m # seconds, minutes

# URL shortener config
url_shortener:
  allowed_protocols:
  - http
  - https
  - ftp
